/*
 * CREATE ALTER DROP INSERT SELECT FROM INTO VALUES 
 * TABLE ADD
 * INT VARCHAR CHAR NOT NULL CONSTRAINT PRIMARY FOREIGN KEY AUTO_INCREMENT REFERENCES
 * OR AND ORDER GROUP BY 
 * id_ nombre_ estado_ numero_ codigo_ tipo_
 */

INSERT INTO 